services:
  postgres:
    image: postgres:16-alpine
    container_name: tms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tms
    ports:
      - '5432:5432'
    volumes:
      - tms_postgres_data:/var/lib/postgresql/data

volumes:
  tms_postgres_data:
